jenkins:
  numExecutors: 2
  remotingSecurity:
    enabled: true
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated"
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "testuser"
        password: "testuser"
      - id: "admin"
        password: "admin"
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
unclassified:
  location:
    url: http://localhost:8080/

tool:
  git:
    installations:
    - home: "git"
      name: "Default"
jobs:
  - script: >
      pipelineJob('pipeline') {
          definition {
              cpsScm {
                  scriptPath 'Jenkinsfile'
                  scm {
                    git {
                        remote { url 'https://github.com/jngirakwizera/video-stream' }
                        branch '*/main'
                        extensions {}
                    }
                  }
              }
          }
      }
